import typer
from pathlib import Path
from jinja2 import Environment, FileSystemLoader
import subprocess
from fapi.constants import TEMPLATES_DIR


def create_venv(project_dir: Path):
    typer.echo("🛠 Creating virtual environment...")
    subprocess.run(["python3", "-m", "venv", ".venv"], cwd=project_dir)


def req_installer(project_dir: Path):
    req_file = project_dir / "requirements.txt"
    pip_path = project_dir / ".venv" / "bin" / "pip"

    typer.echo("📦 Installing dependencies...")
    subprocess.run([str(pip_path), "install", "-r", str(req_file)])

def render_template(src, dest, context):
    env = Environment(loader=FileSystemLoader(TEMPLATES_DIR))
    template = env.get_template(src)
    rendered = template.render(**context)

    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(rendered)

def ensure_fastapi_project():
    if not Path(".fastapi").exists():
        typer.echo("❌ This is not a FastAPI project generated by this CLI.")
        typer.echo("Hint: Run `fapi create <project-name>` first.")
        raise typer.Exit(1)


def scaffold_project(project_dir: Path, context: dict):
    """Render and create the project structure and templates."""
    (project_dir / "app").mkdir(parents=True, exist_ok=True)

    render_template("app/main.py.j2", project_dir / "app/main.py", context)
    (project_dir / "app" / "core").mkdir()
    render_template("app/core/config.py.j2", project_dir / "app/core/config.py", context)
    
    if context["use_db"]:
        (project_dir / "app" / "models").mkdir()
        (project_dir / "app" / "schemas").mkdir()
        (project_dir / "app" / "crud").mkdir()
        render_template("app/crud/user.py.j2", project_dir / "app/crud/user.py", context)
        render_template("app/core/database.py.j2", project_dir / "app/core/database.py", context)
        render_template("app/models/user.py.j2", project_dir / "app/models/user.py", context)
        render_template("app/schemas/user.py.j2", project_dir / "app/schemas/user.py", context)
        
    if context["use_routes"]:
        (project_dir / "app" / "routers").mkdir(exist_ok=True, parents=True)
        (project_dir / "app" / "services").mkdir(exist_ok=True, parents=True)
        render_template("app/routers/users.py.j2", project_dir / "app/routers/users.py", context)
        render_template("app/routers/router.py.j2", project_dir / "app/routers/router.py", context)
        if not context["auth"]:
            render_template("app/services/passwordHash.py.j2", project_dir / "app/services/passwordHash.py", context)

    if context["auth"]:
        render_template("app/core/security.py.j2", project_dir / "app/core/security.py", context)
        (project_dir / "app" / "dependencies").mkdir(exist_ok=True, parents=True)
        render_template("app/dependencies/auth.py.j2", project_dir / "app/dependencies/auth.py", context)
        render_template("app/services/auth.py.j2", project_dir / "app/services/auth.py", context)
        if context["use_db"]:
            render_template("app/schemas/auth.py.j2", project_dir / "app/schemas/auth.py", context)
            render_template("app/routers/auth.py.j2", project_dir / "app/routers/auth.py", context)
        
    if context["websockets"]:
        (project_dir / "app" / "routers").mkdir(exist_ok=True, parents=True)
        render_template("app/routers/websocket.py.j2", project_dir / "app/routers/websocket.py", context)
        
    if context["tasks"] == "celery":
        (project_dir / "app" / "tasks").mkdir(exist_ok=True, parents=True)
        render_template("app/tasks/celery_worker.py.j2", project_dir / "app/tasks/celery_worker.py", context)
    elif context["tasks"] == "arq":
        (project_dir / "app" / "tasks").mkdir(exist_ok=True, parents=True)
        render_template("app/tasks/arq_worker.py.j2", project_dir / "app/tasks/arq_worker.py", context)
        
    if context["mail"]:
        (project_dir / "app" / "services").mkdir(exist_ok=True, parents=True)
        render_template("app/services/email.py.j2", project_dir / "app/services/email.py", context)

    render_template("requirements.txt.j2", project_dir / "requirements.txt", context)
    render_template("app/__init__.py.j2", project_dir / "app/__init__.py", context)


def generate_env(project_dir: Path, context: dict):
    """Generate the .env file based on the project configuration."""
    env_content = f"APP_NAME={context['project_name']}\n"
    db_name = f"{context['project_name']}_db"
    
    if context["use_db"]:
        if context["db_choice"] == "postgres":
            if context["is_async"]:
                env_content += f"DATABASE_URL=postgresql+asyncpg://user:pass@localhost/{db_name}\n"
            else:
                env_content += f"DATABASE_URL=postgresql://user:pass@localhost/{db_name}\n"
        elif context["db_choice"] == "mongodb":
            env_content += f"DATABASE_URL=mongodb://localhost:27017/{db_name}\n"
        else:
            if context["is_async"]:
                env_content += f"DATABASE_URL=sqlite+aiosqlite:///./{db_name}.db\n"
            else:
                env_content += f"DATABASE_URL=sqlite:///./{db_name}.db\n"
            
    if context["redis"] or context["tasks"] in ["celery", "arq"]:
        env_content += "REDIS_URL=redis://localhost:6379/0\n"
        
    if context["auth"]:
        env_content += "SECRET_KEY=supersecretkey\n"
        
    if context["mail"]:
        env_content += (
            "MAIL_USERNAME=user@example.com\n"
            "MAIL_PASSWORD=strong_password\n"
            "MAIL_FROM=info@example.com\n"
            "MAIL_SERVER=smtp.example.com\n"
        )
        
    (project_dir / ".env").write_text(env_content)

